_wandb:
    value:
        cli_version: 0.28.1
        e:
            y2ngzme4tw2hxbmzzp5knsc1ktq2rpaf:
                args:
                    - --precomputed-dir
                    - ../../../data/precomputed_features_pretraining_v5
                    - --num-workers
                    - "8"
                    - --batch-size
                    - "128"
                    - --epochs
                    - "20"
                    - --seed
                    - "42"
                    - --val-frac
                    - "0.1"
                    - --out
                    - ../../../checkpoints/bc_pretrain_alakazam_yushin_ito.pt
                    - --wandb-project
                    - pokemon-tcg-bc
                    - --wandb-name
                    - pretrain-v5
                    - --no-progress
                codePath: archetypes/pretraining/policy_network/bc_train.py
                codePathLocal: bc_train.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "965910667264"
                        used: "742911062016"
                email: sayid.10121012@mahasiswa.unikom.ac.id
                executable: /home/capon/miniconda3/envs/kaggle-pokemon/bin/python
                git:
                    commit: 34601cacfded90fc175547babceadb4c3cc4813e
                    remote: https://github.com/sayidmabrur/pokemon-tcg.git
                gpu: NVIDIA GeForce RTX 3060
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3584
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3060
                      uuid: GPU-2ad13c0d-fd17-3b81-db21-a8c18c2308f5
                host: archlinux
                memory:
                    total: "16678006784"
                os: Linux-7.0.9-arch1-1-x86_64-with-glibc2.43
                program: /home/capon/projects/kaggle/pokemon-tcg-rl-submission-untouched/archetypes/pretraining/policy_network/bc_train.py
                python: CPython 3.12.13
                root: /home/capon/projects/kaggle/pokemon-tcg-rl-submission-untouched/archetypes/pretraining/policy_network
                startedAt: "2026-08-04T10:09:47.543632Z"
                writerId: y2ngzme4tw2hxbmzzp5knsc1ktq2rpaf
        m: []
        python_version: 3.12.13
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
                - 61
                - 62
            "4": 3.12.13
            "5": 0.28.1
            "12": 0.28.1
            "13": linux-x86_64
batch_size:
    value: 128
batches_per_epoch:
    value: 4701
device:
    value: cuda
dropout:
    value: 0.1
duel_episodes:
    value: 0
epochs:
    value: 20
grad_clip:
    value: 1
lr:
    value: 0.001
num_train_samples:
    value: 601669
num_val_samples:
    value: 66471
num_workers:
    value: 8
params:
    value: 2416897
parquet_path:
    value: null
player_name:
    value: null
precomputed_dir:
    value: ../../../data/precomputed_features_pretraining_v5
seed:
    value: 42
shuffle:
    value: true
total_steps:
    value: 94020
val_frac:
    value: 0.1
weight_decay:
    value: 0.01
